import { StyleSheet } from 'react-native';

export const violationModalStyles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  modalCard: {
    width: '100%',
    maxHeight: '88%',
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#CCE6D8',
    paddingHorizontal: 16,
    paddingVertical: 16,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 14,
  },
  modalHeadRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  modalTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    paddingRight: 8,
  },
  modalTitleIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#57c7a8',
  },
  modalCloseBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
  },
  modalTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: '#111827',
    fontFamily: 'CircularStdMedium500',
  },
  modalSub: {
    marginTop: 1,
    marginBottom: 2,
    fontSize: 12,
    lineHeight: 15,
    color: '#64748B',
    fontFamily: 'CircularStdMedium500',
  },
  modalSectionTitle: {
    fontSize: 14,
    lineHeight: 16,
    color: '#1F2937',
    fontFamily: 'CircularStdMedium500',
    marginBottom: 8,
  },
  modalViolationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F3D8A7',
    backgroundColor: '#FFF7E8',
    paddingHorizontal: 10,
    paddingVertical: 9,
    marginBottom: 12,
  },
  modalViolationInfoText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
    color: '#7C2D12',
    fontFamily: 'CircularStdMedium500',
  },
  reasonList: {
    marginBottom: 12,
  },
  reasonItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 11,
    marginBottom: 7,
  },
  reasonItemSelected: {
    borderColor: '#57c7a8',
    backgroundColor: '#ECF9F2',
  },
  reasonDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#94A3B8',
    marginRight: 8,
    backgroundColor: '#FFFFFF',
  },
  reasonDotSelected: {
    backgroundColor: '#57c7a8',
    borderColor: '#57c7a8',
  },
  reasonText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 17,
    color: '#334155',
    fontFamily: 'CircularStdMedium500',
  },
  reasonTextSelected: {
    color: '#166534',
  },
  detailsInput: {
    minHeight: 110,
    borderWidth: 1,
    borderColor: '#DDE5EE',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
    lineHeight: 17,
    color: '#111827',
    fontFamily: 'CircularStdMedium500',
    backgroundColor: '#F8FAFC',
  },
  modalActions: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  modalCancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D5DEE8',
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#475569',
    fontFamily: 'CircularStdMedium500',
  },
  modalSubmitBtn: {
    flex: 1.4,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#57c7a8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubmitText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#FFFFFF',
    fontFamily: 'CircularStdMedium500',
  },
});
