import { StyleSheet } from 'react-native';

export const homeModalStyles = StyleSheet.create({
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 300,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DFE8E4',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 7,
    alignItems: 'center',
  },
  modalIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#EAF8F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  modalIconWarnWrap: {
    backgroundColor: '#FFF7ED',
  },
  modalTitle: {
    fontSize: 22,
    lineHeight: 26,
    color: '#111827',
    fontFamily: 'CircularStdMedium500',
    textAlign: 'center',
  },
  modalText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 19,
    color: '#64748B',
    fontFamily: 'CircularStdMedium500',
    textAlign: 'center',
  },
  modalActions: {
    marginTop: 14,
    width: '100%',
    gap: 10,
  },
  modalGhostButton: {
    height: 42,
    borderRadius: 12,
    borderWidth: 0,
    backgroundColor: '#F2F8F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalGhostText: {
    fontSize: 14,
    lineHeight: 17,
    color: '#2F8F62',
    fontFamily: 'CircularStdMedium500',
  },
  modalPrimaryButton: {
    height: 46,
    borderRadius: 14,
    backgroundColor: '#57c7a8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryText: {
    fontSize: 14,
    lineHeight: 17,
    color: '#FFFFFF',
    fontFamily: 'CircularStdMedium500',
  },
});
