import { StyleSheet } from 'react-native';

export const profileModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(3, 3, 24, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EDF3',
    padding: 16,
  },
  infoModalCard: {
    width: '100%',
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E7EDF3',
    padding: 16,
    gap: 10,
  },
  modalTitle: {
    fontSize: 20,
    lineHeight: 24,
    color: '#111827',
    fontFamily: 'CircularStdMedium500',
    marginBottom: 8,
  },
  modalProfilePreviewWrap: {
    alignItems: 'center',
    marginBottom: 12,
  },
  modalProfilePreview: {
    width: 74,
    height: 74,
    borderRadius: 37,
  },
  modalLabel: {
    fontSize: 13,
    lineHeight: 16,
    color: '#475569',
    fontFamily: 'CircularStdMedium500',
    marginBottom: 6,
  },
  modalInput: {
    height: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDE5EC',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 12,
    fontSize: 14,
    lineHeight: 17,
    color: '#111827',
    fontFamily: 'CircularStdMedium500',
    marginBottom: 10,
  },
  uploadIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#CFEEDF',
    backgroundColor: '#F6FFFA',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    alignSelf: 'center',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
  },
  modalSecondaryButton: {
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDE5EC',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalPrimaryButton: {
    height: 42,
    borderRadius: 10,
    backgroundColor: '#57c7a8',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  modalSecondaryText: {
    fontSize: 14,
    lineHeight: 17,
    color: '#334155',
    fontFamily: 'CircularStdMedium500',
  },
  modalPrimaryText: {
    fontSize: 14,
    lineHeight: 17,
    color: '#FFFFFF',
    fontFamily: 'CircularStdMedium500',
  },
  infoText: {
    fontSize: 14,
    lineHeight: 19,
    color: '#475569',
    fontFamily: 'CircularStdMedium500',
  },
});
